[Content]
Packages=
    https://persistent.oaistatic.com/codex-app-prod/linux/rpm/latest/chatgpt.x86_64.rpm
    jq
    nix
    nix-daemon
    nix-filesystem
    policycoreutils-python-utils
    pulseaudio-utils
