[Content]
Packages=
    1password
    https://kojipkgs.fedoraproject.org/packages/kernel/7.1.13/200.fc44/x86_64/kernel-7.1.13-200.fc44.x86_64.rpm
    https://kojipkgs.fedoraproject.org/packages/kernel/7.1.13/200.fc44/x86_64/kernel-core-7.1.13-200.fc44.x86_64.rpm
    https://kojipkgs.fedoraproject.org/packages/kernel/7.1.13/200.fc44/x86_64/kernel-modules-7.1.13-200.fc44.x86_64.rpm
    https://kojipkgs.fedoraproject.org/packages/kernel/7.1.13/200.fc44/x86_64/kernel-modules-core-7.1.13-200.fc44.x86_64.rpm
    https://kojipkgs.fedoraproject.org/packages/kernel/7.1.13/200.fc44/x86_64/kernel-modules-extra-7.1.13-200.fc44.x86_64.rpm
    jq
    nix
    nix-daemon
    nix-filesystem
    policycoreutils-python-utils
    pulseaudio-utils
    zsh

[Distribution]
Repositories=1password
